---
kind: pipeline
type: docker
name: default


---
kind: pipeline
type: docker
name: build

steps:
  - name: sync_push
    image: alpine/git:1.0.7
    environment:
      REPO_REMOTE: https://github.com/fewensa/rttp.git
    volumes:
      - name: git_credentials
        path: /root/.git-credentials
      - name: git_config
        path: /root/.gitconfig
    when:
      event:
        - push
    commands:
      - git remote add github $REPO_REMOTE
      - git push github $DRONE_BRANCH

  - name: sync_tag
    image: alpine/git:1.0.7
    environment:
      REPO_REMOTE: https://github.com/fewensa/rttp.git
    volumes:
      - name: git_credentials
        path: /root/.git-credentials
      - name: git_config
        path: /root/.gitconfig
    when:
      event:
        - tag
    commands:
      - git remote add github $REPO_REMOTE
      - git fetch origin
      - git push github $DRONE_TAG


volumes:
  - name: git_credentials
    host:
      path: /data/mount/git/.git-credentials
  - name: git_config
    host:
      path: /data/mount/git/.gitconfig

