[package]
name = "rttp-protocol"
version = "0.1.0"
description = "Internal HTTP wire protocol primitives for rttp"
homepage = "https://github.com/fewensa/rttp"
repository = "https://github.com/fewensa/rttp"
license = "MIT"
keywords = ["http"]
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
readme = "README.md"
edition = "2021"

[lib]
name = "rttp_protocol"
path = "src/lib.rs"

[dependencies]
base64 = "0.22"
httpdate = "1.0"
sfv = "0.15.0"
url = "2"
